install.packages("CARS")
cars_dataset<-Cars
pairs(Cars)
cor(Cars)
Reg_MOdel_Cars<- lm(MPG ~ HP+VOL+SP+WT, data = cars_dataset)
summary(cars_dataset)
library(CARS)
vif(Reg_MOdel_Cars)
plot(Reg_MOdel_Cars)
residualPlot(Reg_MOdel_Cars)
avPlots(Reg_MOdel_Cars)
qqplot(Reg_MOdel_Cars)
influenceIndexPlot(Reg_MOdel_Cars)
New_cars<- cars_dataset[-c(77),]
pairs(New_cars)
cor(New_cars)
reg_model_cars_1<- lm(MPG~ HP+VOL+SP, data = New_cars)
summary(reg_model_cars_1)
vif(reg_model_cars_1)
plot(reg_model_cars_1)
residualPlot(reg_model_cars_1)
avPlots(reg_model_cars_1)
qq.plot(reg_model_cars_1)
influenceIndexPlot(reg_model_cars_1)
New_Cars_1<- Cars[-c(77,79),]
pairs(New_Cars_1)
cor(New_Cars_1)
reg_model_cars_2<- lm(MPG~HP+VOL+SP, data = New_Cars_1)
summary(reg_model_cars_2)
vif(reg_model_cars_2)
plot(reg_model_cars_2)
residualPlot(reg_model_cars_2)
avPlots(reg_model_cars_2)
qqPlot(reg_model_cars_2)
influenceIndexPlot(reg_model_cars_2)
New_Cars_data_2<- Cars[-c(77, 79, 80),]
pairs(New_Cars_data_2)
cor(New_Cars_data_2)
reg_model_cars_3<-lm(MPG~HP+VOL+SP,data= New_Cars_data_2)
summary(reg_model_cars_3)
vif(reg_model_cars_3)
plot(reg_model_cars_3)
residualPlot(reg_model_cars_3)
avPlots(reg_model_cars_3)
qqplot(reg_model_cars_3)
influenceIndexPlot(reg_model_cars_3)

